/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guivideo;

import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;
/**
 *
 * @author Verosffy
 */
public class EditEmployee extends javax.swing.JFrame {

    
    
    ArrayList<Job> jobs;
    ArrayList<Employee> employees;
    DecimalFormat formatter;

    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        
           
        formatter=new DecimalFormat("#,###.00");

        jobs = new ArrayList<Job>();
        employees = new ArrayList<Employee>();
        populateArrayList();
        
         String[] jobsArray=new String[jobs.size()];
         for (int i = 0; i < jobs.size(); i++) {
            jobsArray[i]=jobs.get(i).getNameOfJob()+", R"+formatter.format(jobs.get(i).getSalary());
        }
        jCBJob.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
         String[] employeesStringArray=new String[employees.size()];
         for (int i = 0; i < employees.size(); i++) {
            employeesStringArray[i]=employees.get(i).getName()+", "+employees.get(i).getSurname()+
                    formatter.format(employees.get(i).getStaffNr());
        }
        jCBEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(employeesStringArray));
        jCBEmployee.setSelectedIndex(0);
    }
     public void saveEmployeesToFile(){
    
    try{
        FileOutputStream file=new FileOutputStream("Employees.dat");
        ObjectOutputStream outputFile=new ObjectOutputStream(file);
        for (int i = 0; i < employees.size(); i++) {
            
            outputFile.writeObject(employees.get(i));
        }
        outputFile.close();
        
        JOptionPane.showMessageDialog(null, "Succesfully saved!");
        this.dispose();
    }catch(IOException e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
     public void populateArrayList() {
         try{
            FileInputStream file=new FileInputStream("Jobs.dat");
            ObjectInputStream inputFile=new ObjectInputStream(file);
            
            boolean endOfFile=false;
            while(!endOfFile){
                try{
                    jobs.add((Job) inputFile.readObject());
                }catch(EOFException e){
                    endOfFile=true;
                    
                }catch(Exception f){
                    JOptionPane.showMessageDialog(null, "Gond  a jobs.dat fileban");
                }
            }inputFile.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "ioexeption gond a jobs-dat fileban");
        }
        try {
            FileInputStream file2 = new FileInputStream("Employees.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2);

            boolean endOfFile2 = false;
            while (!endOfFile2) {
                try {
                    employees.add((Employee) inputFile2.readObject());
                } catch (EOFException e) {
                    endOfFile2 = true;

                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null,"itt van a gond?");
                }
            }
            inputFile2.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "ioException employees.dat nél");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBEmployee = new javax.swing.JComboBox<>();
        jTFEmployeeName = new javax.swing.JTextField();
        jTFEmployeeSurname = new javax.swing.JTextField();
        jCBJob = new javax.swing.JComboBox<>();
        jTFEmployeeStaff = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee Details");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Edit Employee data:");

        jLabel2.setText("Choose employee:");

        jLabel3.setText("Employee name:");

        jLabel4.setText("Employee surname:");

        jLabel5.setText("Employee job:");

        jLabel6.setText("Employee staff number:");

        jCBEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEmployeeActionPerformed(evt);
            }
        });

        jCBJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBJobActionPerformed(evt);
            }
        });

        jBSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guivideo/save.png"))); // NOI18N
        jBSave.setText("Svae");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guivideo/exit.png"))); // NOI18N
        jButton2.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBEmployee, 0, 251, Short.MAX_VALUE)
                            .addComponent(jTFEmployeeName)
                            .addComponent(jTFEmployeeSurname)
                            .addComponent(jCBJob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFEmployeeStaff)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCBEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jTFEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTFEmployeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCBJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTFEmployeeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEmployeeActionPerformed
      int selectedIndex=jCBEmployee.getSelectedIndex();
      
      jTFEmployeeName.setText(employees.get(selectedIndex).getName());
      jTFEmployeeSurname.setText(employees.get(selectedIndex).getSurname());
      
     
      jTFEmployeeStaff.setText(employees.get(selectedIndex).getStaffNr()+"");
      
      Job job =employees.get(selectedIndex).getJob();
      
      
      int index=0;
        for (int i = 0; i < jobs.size(); i++) {
            if(jobs.get(i).equals(job)){
                index=i;
                break;
            }
        }
        
        jCBJob.setSelectedIndex(index);
        
    }//GEN-LAST:event_jCBEmployeeActionPerformed

    private void jCBJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBJobActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
       if(jTFEmployeeName.getText().isEmpty()||
              jTFEmployeeSurname.getText().isEmpty()||
              jTFEmployeeStaff.getText().isEmpty()||
              jCBEmployee.getSelectedItem()==null)
      {
          JOptionPane.showMessageDialog(null, "You have to enter all fields!");
      }
      else{
           int selectedIndex=jCBEmployee.getSelectedIndex();
           employees.get(selectedIndex).setName(jTFEmployeeName.getText().trim());
           employees.get(selectedIndex).setSurname(jTFEmployeeSurname.getText().trim());
           employees.get(selectedIndex).setStaffNr(Integer.parseInt(jTFEmployeeStaff.getText().trim()));
          Job job=jobs.get(jCBJob.getSelectedIndex());
           employees.get(selectedIndex).setJob(job);
           
           
           saveEmployeesToFile();
           
           
      } 
    }//GEN-LAST:event_jBSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBEmployee;
    private javax.swing.JComboBox<String> jCBJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFEmployeeName;
    private javax.swing.JTextField jTFEmployeeStaff;
    private javax.swing.JTextField jTFEmployeeSurname;
    // End of variables declaration//GEN-END:variables
}
